# Import the relevant libraries

In [1]:
import numpy as np

# Declaring scalars, vectors and matrices

### Scalars

In [3]:
s = 5

In [4]:
s

5

### Vectors

In [21]:
v = np.array([5, -2, 4])

In [22]:
v

array([ 5, -2,  4])

### Matrices

In [23]:
m = np.array([[5,12,6],[-3,0,14]])

In [24]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data Types

In [25]:
type(s)

int

In [26]:
type(v)

numpy.ndarray

In [27]:
type(m)

numpy.ndarray

In [28]:
s_array = np.array(5)
s_array

array(5)

In [29]:
type(s_array)

numpy.ndarray

### Data Shapes

In [30]:
m.shape

(2, 3)

In [31]:
v.shape 

(3,)

In [35]:
s.shape #Error is because scalars have no dimension

AttributeError: 'int' object has no attribute 'shape'

In [37]:
s_array.shape # Empty shape because it is ) dimensional

()

### Creating a column vector

In [32]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [33]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])