# Import the relevant libraries

In [1]:
import numpy as np

## Transposing matrices

In [2]:
A = np.array([[ 5, 12, 6],[-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [5]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [7]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [12]:
C = np.array([[4, -5],[8,12],[-2, -3],[19, 0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [13]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

## Transposing Scalars

In [15]:
s = np.array([5])

In [16]:
s.T

array([5])

## Transposing Vectors

In [17]:
t = np.array([1,2,3])
t

array([1, 2, 3])

In [18]:
t.T

array([1, 2, 3])

In [20]:
t.shape

(3,)

In [22]:
t_reshaped =t.reshape(1,3)
t_reshaped

array([[1, 2, 3]])

In [23]:
t_reshaped.T

array([[1],
       [2],
       [3]])